#ifndef RECONOCIMIENTOTECLADO_H_INCLUDED
#define RECONOCIMIENTOTECLADO_H_INCLUDED

#define FLECHA_ARRIBA 72
#define FLECHA_IZQ 75
#define FLECHA_DER 77
#define FLECHA_ABAJO 80
#define ENTER 13
#define BACKSPACE 8
#define TAB 9

#endif // RECONOCIMIENTOTECLADO_H_INCLUDED
